apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Service
  metadata:
    name: servicebroker-example
    labels:
      app: servicebroker-example
  spec:
    ports:
    - port: 33333
      name: rest
      targetPort: 33333
    selector:
      app: servicebroker-example

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: servicebroker-example
    labels:
      app: servicebroker-example
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: servicebroker-example
      spec:
        containers:
        - name: server
          image: registry.new.dataos.io/datafoundry/servicebroker-example
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - /tmp/service-broker-example
          - -port=33333
          ports:
          - containerPort: 33333

