apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Service
  metadata:
    name: apiserver-servicebroker
    labels:
      api: apiserver-servicebroker
      apiserver: "true"
  spec:
    ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      api: apiserver-servicebroker
      apiserver: "true"

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: apiserver-servicebroker
    labels:
      api: apiserver-servicebroker
      apiserver: "true"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          api: apiserver-servicebroker
          apiserver: "true"
      spec:
        serviceAccountName: "apiserver"
        containers:
        - name: apiserver
          image: registry.new.dataos.io/datafoundry/apiserver-servicebroker:latest
          volumeMounts:
          - name: apiserver-certs
            mountPath: /apiserver.local.config/certificates
            readOnly: true
          command:
          - "./apiserver"
          args:
          - "--etcd-servers=http://etcd-for-apiserver:2379"
          - "--etcd-prefix=/registry/asiainfo.com"
          - "--etcd-cafile="
          - "--etcd-certfile="
          - "--etcd-keyfile="
          - "--secure-port=8443"
          - "--tls-cert-file=/apiserver.local.config/certificates/apiserver.pem"
          - "--tls-private-key-file=/apiserver.local.config/certificates/apiserver-key.pem"
          - "--audit-log-path=-"
          - "--audit-log-maxage=0"
          - "--audit-log-maxbackup=0"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
        volumes:
        - name: apiserver-certs
          secret:
            secretName: apiserver-servicebroker

